### ISSUE TITLE
[Enhancement] Pipeworks Compatibility

### ISSUE THREAD

**Issue by cheapie** [minetest-mods/currency#1]
It would be nice if the shops were compatible with pipeworks (if it's installed). Tubes would be able to place items into the "Your Stock" section, and filters would remove from the "Customers Gave" section (if they ever get ownership added, at least).

**Comment by thatgraemeguy** [comment]
Filters have already had the necessary ownership-related changes made a while ago, so would this enhancement be any easier nowadays?

**Comment by cheapie** [comment]
I think so. I'll see what I can come up with.

**Comment by cheapie** [comment]
Closing this as it is obsoleted by #7.

**Comment by thatgraemeguy** [comment]
Great, thanks cheapie!
