### ISSUE TITLE
Currency mod is non-free

### ISSUE THREAD

**Issue by SmallJoker** [minetest-mods/currency#16]
Missing license for both, code and textures.

**Comment by VanessaE** [comment]
https://gitlab.com/VanessaE/currency/commit/5a97f4610db8b38ad0fff9ffba1969f55ac830a5

source: what's left of Dan's forum thread for this mod: https://forum.minetest.net/viewtopic.php?id=7002

(forum mods can't edit Dan's posts for some reason.  Triggers a forum database error)

**Comment by SmallJoker** [comment]
@VanessaE Thanks. I've too that link in my history and bookmarks but the trash region of the forums is restricted to moderators only.

**Comment by VanessaE** [comment]
Yeah it took me some searching to even find that link.  Odd, I could have sworn I had my own thread for that mod.
