### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/currency#18]
This is now a dep for the new homedecor versions, so I'll want to package it for Debian, and I prefer doing so using upstream-blessed releases and not random commits. (Following a scheme like YYYYMMDD is both simple and efficient.)

Thanks!

**Comment by VanessaE** [comment]
This mod's home is on gitlab, and is already tagged.  https://gitlab.com/VanessaE/currency

**Comment by SnarkBoojum** [comment]
Oh, excellent. I just packaged both currency and basic_materials in Debian, and updated homedecor.
